### ISSUE TITLE
Proposed changes

### ISSUE THREAD

**Issue by kashike** [packson/packson#11]
Rough copy.

``` json
[
    {
        "group": "thaumcraft",
        "id": "thaumcraft",
        "name": "Thaumcraft",
        "version": "1.8-5.0.1",
        "description": "Adding a touch of magic to Minecraft",
        "authors": [
            "Azanor"
        ],
        "credits": [
            "CovertJaguar",
            "Dan Scott",
            "Lorc",
            "bonemouse",
            "Scott Killen",
            "Rorax",
            "chicken_bones"
        ],
        "dependencies": [
            ["Baubles"],
            ["SomeOther", "optional version matcher"]
        ],
        "images": {
            "logo": "TCLogo.png",
            "screenshots": [
                "...",
                "..."
            ]
        }
    }
]
```

**Changes**
- add `group` to replace `owner`
- `owner` -> `id` - The required identifier of the package.
- accept `id` and optional `version` matcher for dependencies
- add required `authors` section
- add optional `credits` section
- add optional `images` section

**Comment by maxov** [comment]
Changes I'd like to make:
- `owner` -> `group`, makes the purpose more clear
- `name` -> `id`, also makes the purpose more clear
- add optional `title`, human-readable title, i.e. `"My Package"`
- add `authors`, but optional. format along the lines of [package.json's authors](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)
- add `credits`, optional. perhaps call it `contributors` instead

I'm not sure about a special images field, those might just belong as special links. Could images refer to within the artifact itself as well as externally?
On dependencies, I think making `version` optional is okay. But `id` and `group` should be required, because the combination of `id` + `group` is unique.

**Comment by maxov** [comment]
#12 was completed, so closing this issue.
